export const INVOICE_MESSAGE = {
  NOT_FOUND_INVOICE: 'NOT_FOUND_INVOICE',
  ITEMS_OUT_OF_STOCK: 'ITEMS_OUT_OF_STOCK',
  PREPARING_ITEMS: 'PREPARING_ITEMS',
  DELIVERING: 'DELIVERING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELED_OUT_OF_STOCK: 'CANCELED_OUT_OF_STOCK',
};
