export const INVOICE_MESSAGE = {
  CREATE_INVOICE_SUCCESS: 'CREATE_INVOICE_SUCCESS',
  CREATE_INVOICE_PAYMENT_SUCCESS: 'CREATE_INVOICE_PAYMENT_SUCCESS',
  NOT_FOUND_INVOICE: 'NOT_FOUND_INVOICE',
  ITEMS_OUT_OF_STOCK: 'ITEMS_OUT_OF_STOCK',
  PREPARING_ITEMS: 'PREPARING_ITEMS',
  DELIVERING: 'DELIVERING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELED_OUT_OF_STOCK: 'CANCELED_OUT_OF_STOCK',
};
