export const USER_ADDRESS_MESSAGE = {
  DUPLICATE_USER_ADDRESS: 'DUPLICATE_USER_ADDRESS',
  NOT_FOUND_USER_ADDRESS: 'NOT_FOUND_USER_ADDRESS',
  DELETE_USER_ADDRESS_SUCCESS: 'DELETE_USER_ADDRESS_SUCCESS',
};
